const { prefix } = require('../../config.json');
const { MessageEmbed } = require('discord.js');
const { red } = require('../../colors.json');

module.exports = {
	config: {
		name: 'valagent',
		usage: `${prefix}valgent [agent name]`,
		category: 'valorant',
		description: 'Look up the information for a Valorant agent.',
		accessableby: 'Verified',
	},
	run: async (bot, message) => {
		try {
			const Agents = {
				breach: {
					name: 'Breach',
					origin: ':flag_se: Sweden',
					type: 'Initiator',
					type_icon: 'https://i.imgur.com/6hguAch.png',
					description: 'Breach fires powerful, targeted kinetic blasts to aggressively clear a path through enemy ground. The damage and disruption he inflicts ensures no fight is ever fair.',
					image: 'https://i.imgur.com/H5lfrPZ.png',
					ccost: '100',
					cability: 'Aftershock',
					cabilitydescription: 'Fusion Charge through wall. The burst does heavy damage to anyone in its range',
					qcost: '200',
					qability: 'Flashpoint',
					qabilitydescription: 'Flash through the wall. Blind all players looking at it',
					ecost: 'Free, 35 sec Cooldown.',
					eability: 'Fault Line',
					eabilitydescription: 'Quake, which dazing all players in its zone',
					xcost: '7 Ult Points',
					xability: 'Rolling Thunder',
					xabilitydescription: 'Cascading Quake through all terrain in a large cone. The quake dazes and knocks up anyone caught in it.',
				},
				brimstone: {
					name: 'Brimstone',
					origin: ':flag_us: United States',
					type: 'Controller',
					type_icon: 'https://i.imgur.com/z4J50WM.png',
					description: 'Brimstone’s orbital arsenal ensures his squad always has the advantage. His ability to deliver utility precisely and safely make him the unmatched boots-on-the-ground commander.',
					image: 'https://i.imgur.com/rDoVhLm.png',
					ccost: '100',
					cability: 'Stim Beacon',
					cabilitydescription: 'Stim Beacon, creates on landing a field which grant players RapidFire',
					qcost: '200',
					qability: 'Incendiary',
					qabilitydescription: 'Grenate, creating a lingering fire zone that damages players within the zone',
					ecost: '1 Free, 100 for extra charges.',
					eability: 'Sky Smoke',
					eabilitydescription: 'Smoke, launching long-lasting smoke clouds that block vision in the selected area',
					xcost: '6 Ult Points',
					xability: 'Orbital Strike',
					xabilitydescription: 'Orbital Strike, dealing high damage-over-time to players cought in the selcted area',
				},
				cypher: {
					name: 'Cypher',
					origin: ':flag_ma: Morocco',
					type: 'Sentinel',
					type_icon: 'https://i.imgur.com/21h1W6m.png',
					description: 'Cypher is a one-man surveillance network who keeps tabs on the enemy’s every move. No secret is safe. No maneuver goes unseen. Cypher is always watching.',
					image: 'https://i.imgur.com/2DVIhYi.png',
					ccost: '200',
					cability: 'Trapwire',
					cabilitydescription: 'Enemy players who cross a tripwire will be tethered, and dazed after a short period if they do not destroy the device in time',
					qcost: '100',
					qability: 'Cyber Cage',
					qabilitydescription: 'Create a zone that blocks vision and slows enemies who pass through it.',
					ecost: 'Free, Can be picked up and re-used.',
					eability: 'Spycam',
					eabilitydescription: 'Camera with a dart, dart will reveal the location of any player struck by the dart',
					xcost: '7 Ult Points',
					xability: 'Neural Theft',
					xabilitydescription: 'Use on a dead enemy in your crosshairs to reveal the location of all living enemy players',
				},
				jett: {
					name: 'Jett',
					origin: ':flag_kr: South Korea',
					type: 'Duelist',
					type_icon: 'https://i.imgur.com/xlF2Wzp.png',
					description: 'Jett’s agile and evasive fighting style lets her take risks no one else can. She runs circles around every skirmish, cutting enemies up before they even know what hit them.',
					image: 'https://i.imgur.com/gSYYGDi.png',
					ccost: '100',
					cability: 'Cloudburst',
					cabilitydescription: 'Throw a projectile that expands into a brief vision-blocking cloud',
					qcost: '100',
					qability: 'Updraft',
					qabilitydescription: 'Propel Jett into the air',
					ecost: 'Free, usable once per round, refreshed on 2 kills.',
					eability: 'Tailwind',
					eabilitydescription: 'Propel Jett in the direction she is moving',
					xcost: '7 Ult Points',
					xability: 'Bladestorm',
					xabilitydescription: 'High accurate throwing kniifes, recharge on killing an opponent',
				},
				omen: {
					name: 'Omen',
					origin: 'Unknown',
					type: 'Controller',
					type_icon: 'https://i.imgur.com/z4J50WM.png',
					description: 'Omen hunts in the shadows. He renders enemies blind, teleports across the field, then lets paranoia take hold as foes scramble to uncover where it might strike next.',
					image: 'https://i.imgur.com/AmmJBCJ.png',
					ccost: '100',
					cability: 'Shrouded Step',
					cabilitydescription: 'Shadow walk ability and see its range indicator',
					qcost: '200',
					qability: 'Paranoia',
					qabilitydescription: 'Fires a shadow projectile forward, reducing vision range of all players it touches.',
					ecost: 'Free 2 Charges, 30 sec cooldown on charge refresh.',
					eability: 'Dark Cover',
					eabilitydescription: 'Shadow Orb, creating a shadow sphere that blocks vision',
					xcost: '7 Ult Points',
					xability: 'Rolling Thunder',
					xabilitydescription: 'Teleport to any point on the map',
				},
				pheonix: {
					name: 'Pheonix',
					origin: ':flag_gb: United Kingdom',
					type: 'Duelist',
					type_icon: 'https://i.imgur.com/xlF2Wzp.png',
					description: 'Phoenix’s star power shines through in his fighting style, igniting the battlefield with flash and flare. Whether he’s got backup or not, he’s rushing in to fight on his own terms.',
					image: 'https://i.imgur.com/d9ziukF.png',
					ccost: '200',
					cability: 'Blaze',
					qcost: '200',
					qability: 'Curveball',
					ecost: 'Free, usable once per round, refreshed on 2 kills.',
					eability: 'Hot hands',
					xcost: '6 Ult Points',
					xability: 'Run it back',
					xabilitydescription: 'Creates a clone, which can die one time',
				},
				raze: {
					name: 'Raze',
					origin: ':flag_br: Brazil',
					type: 'Duelist',
					type_icon: 'https://i.imgur.com/xlF2Wzp.png',
					description: 'Raze loves explosives. With her blunt-force-trauma playstyle, she excels at flushing entrenched enemies and clearing tight spaces with a generous dose of "boom".',
					image: 'https://i.imgur.com/f4Rxfdw.png',
					ccost: '200',
					cability: 'Boom Bot',
					qcost: '200',
					qability: 'Blast Pack',
					ecost: '1 free per round, recharge on 2 kills.',
					eability: 'Paint Shells',
					xcost: '6 Ult Points',
					xability: 'Showstopper',
					xabilitydescription: 'Rocket Launcher',
				},
				sage: {
					name: 'Sage',
					origin: ':flag_cn: China',
					type: 'Sentinel',
					type_icon: 'https://i.imgur.com/21h1W6m.png',
					description: 'Sage creates safety for herself and her team wherever she goes. Able to revive fallen friends and stave off forceful assaults, she provides a calm center to a hellish battlefield.',
					image: 'https://i.imgur.com/YNx8On6.png',
					ccost: '400',
					cability: 'Barrier Orb',
					qcost: '100',
					qability: 'Slow Orb',
					ecost: 'Free, 45 sec cooldown.',
					eability: 'Healing Orb',
					xcost: '7 Ult Points',
					xability: 'Resurrection',
					xabilitydescription: 'Rescue a teammate',
				},
				sova: {
					name: 'Sova',
					origin: ':flag_ru: Russia',
					type: 'Initiator',
					type_icon: 'https://i.imgur.com/6hguAch.png',
					description: 'Sova tracks, finds, and eliminates enemies with ruthless efficiency and precision. His custom bow and incredible scouting abilities ensure that even if you run, you cannot hide.',
					image: 'https://i.imgur.com/W1Ov2Te.png',
					ccost: '300',
					cability: 'Owl Drone',
					qcost: '100',
					qability: 'Shock Bolt',
					ecost: 'Free, 35 sec cooldown.',
					eability: 'Recon Bolt',
					xcost: '7 Ult Points',
					xability: 'Hunter’s Fury',
					xabilitydescription: 'A bow with three long-range, wall-piercing energy blasts.',
				},
				viper: {
					name: 'Viper',
					origin: ':flag_us: United States',
					type: 'Controller',
					type_icon: 'https://i.imgur.com/z4J50WM.png',
					description: 'Viper deploys an array of poisonous chemical devices to control the battlefield and cripple the enemy’s vision. If the toxins don’t kill her prey, her mind games surely will.',
					image: 'https://i.imgur.com/KSt8xD6.png',
					ccost: '100',
					cability: 'Snake Bite',
					qcost: '200',
					qability: 'Poison Cloud',
					ecost: 'Placeable once per round.',
					eability: 'Toxic Screen',
					xcost: '7 Ult Points',
					xability: 'Viper’s Pit',
					xabilitydescription: 'Creating a large cloud that reduces the vision range and maximum health of players inside of it.',
				},
			};

			const name = message.content.toLowerCase().substr(prefix.length + 9);
			const valagent = Agents[name];

			const embed = new MessageEmbed()
				.setColor(red)
				.setTitle(valagent.name)
				.setThumbnail('https://i.imgur.com/Zg07kqa.png')
				.setDescription(`**Origin**\n${valagent.origin}\n
				**Type**\n${valagent.type}\n
				**Abilities**\n${valagent.cability}\n - Cost: ${valagent.ccost}\n${valagent.qability}\n - Cost: ${valagent.qcost}\n${valagent.eability}\n - Cost: ${valagent.ecost}\n${valagent.xability} (Ultimate)\n - Cost: ${valagent.xcost}\n
				**Description**\n${valagent.description}`)
				.setImage(valagent.image);
			message.channel.send(embed);
		} catch (error) {
			message.channel.send('I couldn\'t find that agent.');
		}
	},
};
